"""Spec rotation script — retire an active round and launch the next one.

Closes the given round (sets `ends` to today), generates a fresh 15-spec set
for the new round using the next seed block, writes all files, and optionally
announces via Discord.

Usage:
    python scripts/rotate_round.py --close round_001 --new round_004 \\
        --metric mass_grams --seeds-base 1000

    # Dry run (preview only, writes nothing):
    python scripts/rotate_round.py --close round_001 --new round_004 \\
        --metric mass_grams --seeds-base 1000 --dry-run

Environment:
    DISCORD_WEBHOOK_URL  If set, posts a rotation announcement embed.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path

# Repo root is two levels up from scripts/
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from specs.generator import batch_generate  # noqa: E402


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ROUNDS_DIR = REPO_ROOT / "rounds"
SPECS_DIR = REPO_ROOT / "specs"

METRICS = {
    "mass_grams": {
        "direction": "minimize",
        "description_suffix": "Minimize part mass while satisfying FEA safety requirements.",
    },
    "stiffness_to_weight": {
        "direction": "maximize",
        "description_suffix": "Maximize stiffness-to-weight ratio — structural efficiency under load.",
    },
    "deflection_mm": {
        "direction": "minimize",
        "description_suffix": "Minimize tip deflection — maximize raw structural stiffness.",
    },
}

TIER_CONFIG = {
    "easy":   {"count": 5,  "offset": 0},
    "medium": {"count": 6,  "offset": 100},
    "hard":   {"count": 4,  "offset": 200},
}

ROUND_NAMES = {
    "mass_grams":         "Mass Minimization",
    "stiffness_to_weight": "Structural Efficiency",
    "deflection_mm":      "Deflection",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_round(round_id: str) -> dict:
    path = ROUNDS_DIR / f"{round_id}.json"
    if not path.exists():
        raise FileNotFoundError(f"Round file not found: {path}")
    return json.loads(path.read_text())


def _save_round(round_id: str, data: dict, dry_run: bool) -> None:
    path = ROUNDS_DIR / f"{round_id}.json"
    if dry_run:
        print(f"[dry-run] would write {path}")
        return
    path.write_text(json.dumps(data, indent=2))
    print(f"Wrote {path}")


def _close_round(round_id: str, today: str, dry_run: bool) -> dict:
    data = _load_round(round_id)
    data["status"] = "closed"
    data["ends"] = today
    _save_round(round_id, data, dry_run)
    return data


def _generate_round(
    round_id: str,
    metric: str,
    seeds_base: int,
    today: str,
    dry_run: bool,
) -> dict:
    meta = METRICS[metric]
    round_num = int(round_id.split("_")[-1])  # "round_004" → 4
    prefix = f"r{round_num:02d}"

    spec_ids: list[str] = []
    out_dir = SPECS_DIR / round_id
    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    for tier, cfg in TIER_CONFIG.items():
        seed = seeds_base + cfg["offset"]
        specs = batch_generate(
            n=cfg["count"],
            tier=tier,
            seed=seed,
            id_prefix=f"{prefix}",
            scoring_metric=metric,
        )
        for spec in specs:
            spec_ids.append(spec["id"])
            spec_path = out_dir / f"{spec['id']}.json"
            if dry_run:
                print(f"[dry-run] would write {spec_path}")
            else:
                spec_path.write_text(json.dumps(spec, indent=2))
                print(f"  wrote {spec_path}")

    round_data = {
        "id": round_id,
        "name": f"Round {round_num:03d} — {ROUND_NAMES.get(metric, metric)}",
        "description": meta["description_suffix"],
        "metric": metric,
        "direction": meta["direction"],
        "status": "active",
        "starts": today,
        "ends": None,
        "spec_ids": spec_ids,
        "tiers": {
            tier: {
                "count": cfg["count"],
                "seeds_base": seeds_base + cfg["offset"],
            }
            for tier, cfg in TIER_CONFIG.items()
        },
        "notes": (
            f"Generated by scripts/rotate_round.py. "
            f"Metric: {metric}. Seeds: easy={seeds_base}, "
            f"medium={seeds_base + 100}, hard={seeds_base + 200}."
        ),
    }
    _save_round(round_id, round_data, dry_run)
    return round_data


def _discord_announce(
    closed_id: str,
    new_id: str,
    metric: str,
    spec_count: int,
    dry_run: bool,
) -> None:
    webhook_url = os.environ.get("DISCORD_WEBHOOK_URL", "")
    if not webhook_url:
        print("DISCORD_WEBHOOK_URL not set — skipping Discord announcement")
        return

    metric_display = {
        "mass_grams": "Mass (g) — minimize",
        "stiffness_to_weight": "Stiffness/Weight — maximize",
        "deflection_mm": "Deflection (mm) — minimize",
    }.get(metric, metric)

    payload = {
        "embeds": [
            {
                "title": f"Round rotation: {new_id} is now live",
                "description": (
                    f"**{closed_id}** has been retired. "
                    f"**{new_id}** opens with {spec_count} fresh specs."
                ),
                "color": 0x5865F2,
                "fields": [
                    {"name": "Metric", "value": metric_display, "inline": True},
                    {"name": "Specs", "value": str(spec_count), "inline": True},
                ],
                "footer": {"text": "Forge — Competitive Parametric CAD"},
                "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            }
        ]
    }

    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        webhook_url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    if dry_run:
        print(f"[dry-run] would POST Discord embed: {closed_id} closed, {new_id} live")
        return

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status in (200, 204):
                print(f"Discord announcement posted ({resp.status})")
            else:
                print(f"Discord returned unexpected status {resp.status}")
    except Exception as exc:
        print(f"Discord announcement failed: {exc}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Rotate a Forge competition round.")
    parser.add_argument("--close", required=True, metavar="ROUND_ID",
                        help="Round to retire, e.g. round_001")
    parser.add_argument("--new", required=True, metavar="ROUND_ID",
                        help="New round ID to create, e.g. round_004")
    parser.add_argument("--metric", required=True,
                        choices=list(METRICS),
                        help="Scoring metric for the new round")
    parser.add_argument("--seeds-base", required=True, type=int, metavar="N",
                        help="Base seed for the new round (easy=N, medium=N+100, hard=N+200)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview what would happen without writing files")
    args = parser.parse_args()

    today = date.today().isoformat()
    dry = args.dry_run

    print(f"{'[DRY RUN] ' if dry else ''}Closing {args.close} → launching {args.new}")
    print(f"  metric={args.metric}, seeds_base={args.seeds_base}, date={today}")
    print()

    # 1. Close the old round
    _close_round(args.close, today, dry)

    # 2. Generate and write the new round
    new_data = _generate_round(args.new, args.metric, args.seeds_base, today, dry)
    spec_count = len(new_data["spec_ids"])

    # 3. Announce
    _discord_announce(args.close, args.new, args.metric, spec_count, dry)

    print()
    print(f"Done. {spec_count} specs written for {args.new}.")
    if not dry:
        print()
        print("Next steps:")
        print(f"  git add rounds/{args.close}.json rounds/{args.new}.json specs/{args.new}/")
        print(f"  git commit -m 'Rotate {args.close} → {args.new} ({args.metric})'")
        print(f"  git push")


if __name__ == "__main__":
    main()
